<?php
    $lang['number']   = 'Rechnungsnummer';
    $lang['date']     = 'Rechnungsdatum';
    $lang['period']     = 'Zeitraum';
    $lang['ve']     = 'Vermietungseinheit';
    $lang['time']     = 'Rechnungs-Uhrzeit';
    $lang['due']      = 'Fälligkeitsdatum';
    $lang['to']       = 'Eigentümer';
    $lang['from']     = 'Rechnung von';
    $lang['product']  = 'Leistung';
    $lang['qty']      = 'Anteil in %';
    $lang['price']    = 'Summe';
    $lang['discount'] = 'Rabatt';
    $lang['vat']      = 'MwSt';
    $lang['total']    = 'Gesamtbetrag';
    $lang['page']     = 'Seite';
    $lang['page_of']  = 'von';
    $lang['share']    = '%';
