<?php
    $lang['number']   = 'Reference';
    $lang['date']     = 'Billing date';
    $lang['period']     = 'Period';
    $lang['ve']     = 'Rental unit';
    $lang['time']     = 'Billing time';
    $lang['due']      = 'Due date';
    $lang['to']       = 'Owner';
    $lang['from']     = 'Billing from';
    $lang['product']  = 'Description';
    $lang['qty']      = 'Share in %';
    $lang['price']    = 'Price';
    $lang['discount'] = 'Discount';
    $lang['vat']      = 'Vat';
    $lang['total']    = 'Total';
    $lang['page']     = 'Page';
    $lang['page_of']  = 'of';
    $lang['share']    = '%';
